

let mockCards = [
	{
		id: 1,
		deck_id: 1,
		question: "What is the Capital of Washington?",
		answer: "Olympia",
		seen: false,
		correct: false,
	},
	{
		id: 2,
		deck_id: 1,
		question: "What is the Capital of Florida?",
		answer: "Tallahassee",
		seen: false,
		correct: false,
	},
	{
		id: 3,
		deck_id: 1,
		question: "What is the Capital of New York?",
		answer: "Albany",
		seen: false,
		correct: false,
	},
	{
		id: 4,
		deck_id: 1,
		question: "What is the Capital of Arizona?",
		answer: "Phoenix",
		seen: false,
		correct: false,
	},
	{
		id: 5,
		deck_id: 2,
		question: "Name 3 different Hooks in React?",
		answer: " useState, useEffects, useRef ",
		seen: false,
		correct: false,
	},
	{
		id: 6,
		deck_id: 2,
		question: "How do you create a multi line comment in JavaScript?",
		answer: 'With two forward slashes " /* */ " ',
		seen: false,
		correct: false,
	},
	{
		id: 7,
		deck_id: 2,
		question: "What method convert a string into lowercase characters?",
		answer: ".toLowerCase()",
		seen: false,
		correct: false,
	},
	{
		id: 8,
		deck_id: 3,
		question: "When is it appropriate for a driver to use his vehicle's horn?",
		answer: "Only when necessary to avoid collisions or to try and alert other drivers of your presence",
		seen: false,
		correct: false,
	},
	{
		id: 9,
		deck_id: 3,
		question: "When should you assume that other driver's will give you the right of way?",
		answer: "Never",
		seen: false,
		correct: false,
	},
	{
		id: 10,
		deck_id: 3,
		question: "You should __ your following distance when you encounter other drivers who may be potentially dangerous",
		answer: "increase",
		seen: false,
		correct: false,
	},
	{
		id: 11,
		deck_id: 4,
		question: "JS Q",
		answer: "JS A",
		seen: false,
		correct: false,
	},
	{
		id: 12,
		deck_id: 4,
		question: "JS Q",
		answer: "JS A",
		seen: false,
		correct: false,
	},
	{
		id: 13,
		deck_id: 4,
		question: "JS Q",
		answer: "JS A",
		seen: false,
		correct: false,
	},
	{
		id: 14,
		deck_id: 1,
		question: "What is the Capital of Illinois?",
		answer: "Springfield",
		seen: false,
		correct: false,
	},
	{
		id: 15,
		deck_id: 1,
		question: "What is the Capital of Louisiana?",
		answer: "Baton Rouge",
		seen: false,
		correct: false,
	},
	{
		id: 16,
		deck_id: 1,
		question: "What is the Capital of Montana?",
		answer: "Helena",
		seen: false,
		correct: false
	}

]
export default mockCards